server:
  #配置服务器启动端口
  port: 9090
  servlet:
    context-path: /
  #配置访问的上下文路径，就是localhost:9090后面需要的上下文路径
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #thymeleaf这样配置就可以直接访问static下的HTML(和mvc访问方式二选一)
    prefix: classpath:/static/
    suffix: .html
  #视图层控制 用mvc方式访问templates下的HTML
  mvc:
      view:
        prefix: classpath:/templates/
        suffix: .html
      static-path-pattern: /static/**
author:
  name: huqb
  age: 27
  sex: man

mybatis:
  type-aliases-package: com.huqb.logindemo.model
